// src/lib/addressData.ts
// Cascading country → state/province → city data
// Focused on fishing tournament markets: US, Canada, Australia, and major countries

export interface CountryData {
  code: string;
  name: string;
  stateLabel: string; // "State", "Province", "Territory", etc.
  cityLabel: string;
}

export const COUNTRIES: CountryData[] = [
  { code: 'US', name: 'United States', stateLabel: 'State', cityLabel: 'City' },
  { code: 'CA', name: 'Canada', stateLabel: 'Province / Territory', cityLabel: 'City' },
  { code: 'AU', name: 'Australia', stateLabel: 'State / Territory', cityLabel: 'City' },
  { code: 'MX', name: 'Mexico', stateLabel: 'State', cityLabel: 'City' },
  { code: 'GB', name: 'United Kingdom', stateLabel: 'Country / Region', cityLabel: 'City' },
  { code: 'NZ', name: 'New Zealand', stateLabel: 'Region', cityLabel: 'City' },
  { code: 'ZA', name: 'South Africa', stateLabel: 'Province', cityLabel: 'City' },
  { code: 'BR', name: 'Brazil', stateLabel: 'State', cityLabel: 'City' },
  { code: 'DE', name: 'Germany', stateLabel: 'State', cityLabel: 'City' },
  { code: 'FR', name: 'France', stateLabel: 'Region', cityLabel: 'City' },
  { code: 'JP', name: 'Japan', stateLabel: 'Prefecture', cityLabel: 'City' },
];

// States/Provinces per country
export const STATES: Record<string, { code: string; name: string }[]> = {
  US: [
    { code: 'AL', name: 'Alabama' }, { code: 'AK', name: 'Alaska' },
    { code: 'AZ', name: 'Arizona' }, { code: 'AR', name: 'Arkansas' },
    { code: 'CA', name: 'California' }, { code: 'CO', name: 'Colorado' },
    { code: 'CT', name: 'Connecticut' }, { code: 'DE', name: 'Delaware' },
    { code: 'FL', name: 'Florida' }, { code: 'GA', name: 'Georgia' },
    { code: 'HI', name: 'Hawaii' }, { code: 'ID', name: 'Idaho' },
    { code: 'IL', name: 'Illinois' }, { code: 'IN', name: 'Indiana' },
    { code: 'IA', name: 'Iowa' }, { code: 'KS', name: 'Kansas' },
    { code: 'KY', name: 'Kentucky' }, { code: 'LA', name: 'Louisiana' },
    { code: 'ME', name: 'Maine' }, { code: 'MD', name: 'Maryland' },
    { code: 'MA', name: 'Massachusetts' }, { code: 'MI', name: 'Michigan' },
    { code: 'MN', name: 'Minnesota' }, { code: 'MS', name: 'Mississippi' },
    { code: 'MO', name: 'Missouri' }, { code: 'MT', name: 'Montana' },
    { code: 'NE', name: 'Nebraska' }, { code: 'NV', name: 'Nevada' },
    { code: 'NH', name: 'New Hampshire' }, { code: 'NJ', name: 'New Jersey' },
    { code: 'NM', name: 'New Mexico' }, { code: 'NY', name: 'New York' },
    { code: 'NC', name: 'North Carolina' }, { code: 'ND', name: 'North Dakota' },
    { code: 'OH', name: 'Ohio' }, { code: 'OK', name: 'Oklahoma' },
    { code: 'OR', name: 'Oregon' }, { code: 'PA', name: 'Pennsylvania' },
    { code: 'RI', name: 'Rhode Island' }, { code: 'SC', name: 'South Carolina' },
    { code: 'SD', name: 'South Dakota' }, { code: 'TN', name: 'Tennessee' },
    { code: 'TX', name: 'Texas' }, { code: 'UT', name: 'Utah' },
    { code: 'VT', name: 'Vermont' }, { code: 'VA', name: 'Virginia' },
    { code: 'WA', name: 'Washington' }, { code: 'WV', name: 'West Virginia' },
    { code: 'WI', name: 'Wisconsin' }, { code: 'WY', name: 'Wyoming' },
    { code: 'DC', name: 'District of Columbia' },
    { code: 'PR', name: 'Puerto Rico' }, { code: 'VI', name: 'U.S. Virgin Islands' },
    { code: 'GU', name: 'Guam' },
  ],
  CA: [
    { code: 'AB', name: 'Alberta' }, { code: 'BC', name: 'British Columbia' },
    { code: 'MB', name: 'Manitoba' }, { code: 'NB', name: 'New Brunswick' },
    { code: 'NL', name: 'Newfoundland and Labrador' }, { code: 'NT', name: 'Northwest Territories' },
    { code: 'NS', name: 'Nova Scotia' }, { code: 'NU', name: 'Nunavut' },
    { code: 'ON', name: 'Ontario' }, { code: 'PE', name: 'Prince Edward Island' },
    { code: 'QC', name: 'Quebec' }, { code: 'SK', name: 'Saskatchewan' },
    { code: 'YT', name: 'Yukon' },
  ],
  AU: [
    { code: 'ACT', name: 'Australian Capital Territory' },
    { code: 'NSW', name: 'New South Wales' },
    { code: 'NT', name: 'Northern Territory' },
    { code: 'QLD', name: 'Queensland' },
    { code: 'SA', name: 'South Australia' },
    { code: 'TAS', name: 'Tasmania' },
    { code: 'VIC', name: 'Victoria' },
    { code: 'WA', name: 'Western Australia' },
  ],
  MX: [
    { code: 'AGU', name: 'Aguascalientes' }, { code: 'BCN', name: 'Baja California' },
    { code: 'BCS', name: 'Baja California Sur' }, { code: 'CAM', name: 'Campeche' },
    { code: 'CHP', name: 'Chiapas' }, { code: 'CHH', name: 'Chihuahua' },
    { code: 'CMX', name: 'Ciudad de México' }, { code: 'COA', name: 'Coahuila' },
    { code: 'COL', name: 'Colima' }, { code: 'DUR', name: 'Durango' },
    { code: 'GUA', name: 'Guanajuato' }, { code: 'GRO', name: 'Guerrero' },
    { code: 'HID', name: 'Hidalgo' }, { code: 'JAL', name: 'Jalisco' },
    { code: 'MEX', name: 'Estado de México' }, { code: 'MIC', name: 'Michoacán' },
    { code: 'MOR', name: 'Morelos' }, { code: 'NAY', name: 'Nayarit' },
    { code: 'NLE', name: 'Nuevo León' }, { code: 'OAX', name: 'Oaxaca' },
    { code: 'PUE', name: 'Puebla' }, { code: 'QUE', name: 'Querétaro' },
    { code: 'ROO', name: 'Quintana Roo' }, { code: 'SLP', name: 'San Luis Potosí' },
    { code: 'SIN', name: 'Sinaloa' }, { code: 'SON', name: 'Sonora' },
    { code: 'TAB', name: 'Tabasco' }, { code: 'TAM', name: 'Tamaulipas' },
    { code: 'TLA', name: 'Tlaxcala' }, { code: 'VER', name: 'Veracruz' },
    { code: 'YUC', name: 'Yucatán' }, { code: 'ZAC', name: 'Zacatecas' },
  ],
  GB: [
    { code: 'ENG', name: 'England' }, { code: 'SCT', name: 'Scotland' },
    { code: 'WLS', name: 'Wales' }, { code: 'NIR', name: 'Northern Ireland' },
  ],
  NZ: [
    { code: 'AUK', name: 'Auckland' }, { code: 'BOP', name: 'Bay of Plenty' },
    { code: 'CAN', name: 'Canterbury' }, { code: 'GIS', name: 'Gisborne' },
    { code: 'HKB', name: "Hawke's Bay" }, { code: 'MBH', name: 'Marlborough' },
    { code: 'MWT', name: 'Manawatu-Whanganui' }, { code: 'NSN', name: 'Nelson' },
    { code: 'NTL', name: 'Northland' }, { code: 'OTA', name: 'Otago' },
    { code: 'STL', name: 'Southland' }, { code: 'TAS', name: 'Tasman' },
    { code: 'TKI', name: 'Taranaki' }, { code: 'WGN', name: 'Wellington' },
    { code: 'WKO', name: 'Waikato' }, { code: 'WTC', name: 'West Coast' },
  ],
  ZA: [
    { code: 'EC', name: 'Eastern Cape' }, { code: 'FS', name: 'Free State' },
    { code: 'GP', name: 'Gauteng' }, { code: 'KZN', name: 'KwaZulu-Natal' },
    { code: 'LP', name: 'Limpopo' }, { code: 'MP', name: 'Mpumalanga' },
    { code: 'NC', name: 'Northern Cape' }, { code: 'NW', name: 'North West' },
    { code: 'WC', name: 'Western Cape' },
  ],
  BR: [
    { code: 'AC', name: 'Acre' }, { code: 'AL', name: 'Alagoas' },
    { code: 'AM', name: 'Amazonas' }, { code: 'AP', name: 'Amapá' },
    { code: 'BA', name: 'Bahia' }, { code: 'CE', name: 'Ceará' },
    { code: 'DF', name: 'Distrito Federal' }, { code: 'ES', name: 'Espírito Santo' },
    { code: 'GO', name: 'Goiás' }, { code: 'MA', name: 'Maranhão' },
    { code: 'MG', name: 'Minas Gerais' }, { code: 'MS', name: 'Mato Grosso do Sul' },
    { code: 'MT', name: 'Mato Grosso' }, { code: 'PA', name: 'Pará' },
    { code: 'PB', name: 'Paraíba' }, { code: 'PE', name: 'Pernambuco' },
    { code: 'PI', name: 'Piauí' }, { code: 'PR', name: 'Paraná' },
    { code: 'RJ', name: 'Rio de Janeiro' }, { code: 'RN', name: 'Rio Grande do Norte' },
    { code: 'RO', name: 'Rondônia' }, { code: 'RR', name: 'Roraima' },
    { code: 'RS', name: 'Rio Grande do Sul' }, { code: 'SC', name: 'Santa Catarina' },
    { code: 'SE', name: 'Sergipe' }, { code: 'SP', name: 'São Paulo' },
    { code: 'TO', name: 'Tocantins' },
  ],
  DE: [
    { code: 'BB', name: 'Brandenburg' }, { code: 'BE', name: 'Berlin' },
    { code: 'BW', name: 'Baden-Württemberg' }, { code: 'BY', name: 'Bavaria' },
    { code: 'HB', name: 'Bremen' }, { code: 'HE', name: 'Hesse' },
    { code: 'HH', name: 'Hamburg' }, { code: 'MV', name: 'Mecklenburg-Vorpommern' },
    { code: 'NI', name: 'Lower Saxony' }, { code: 'NW', name: 'North Rhine-Westphalia' },
    { code: 'RP', name: 'Rhineland-Palatinate' }, { code: 'SH', name: 'Schleswig-Holstein' },
    { code: 'SL', name: 'Saarland' }, { code: 'SN', name: 'Saxony' },
    { code: 'ST', name: 'Saxony-Anhalt' }, { code: 'TH', name: 'Thuringia' },
  ],
  FR: [
    { code: 'ARA', name: 'Auvergne-Rhône-Alpes' }, { code: 'BFC', name: 'Bourgogne-Franche-Comté' },
    { code: 'BRE', name: 'Bretagne' }, { code: 'CVL', name: 'Centre-Val de Loire' },
    { code: 'COR', name: 'Corse' }, { code: 'GES', name: 'Grand-Est' },
    { code: 'HDF', name: 'Hauts-de-France' }, { code: 'IDF', name: 'Île-de-France' },
    { code: 'NAQ', name: 'Nouvelle-Aquitaine' }, { code: 'NOR', name: 'Normandie' },
    { code: 'OCC', name: 'Occitanie' }, { code: 'PDL', name: 'Pays de la Loire' },
    { code: 'PAC', name: "Provence-Alpes-Côte d'Azur" },
  ],
  JP: [
    { code: 'HKD', name: 'Hokkaido' }, { code: 'AOI', name: 'Aomori' },
    { code: 'IWT', name: 'Iwate' }, { code: 'MYG', name: 'Miyagi' },
    { code: 'AKT', name: 'Akita' }, { code: 'YMG', name: 'Yamagata' },
    { code: 'FKS', name: 'Fukushima' }, { code: 'IBR', name: 'Ibaraki' },
    { code: 'TCG', name: 'Tochigi' }, { code: 'GNM', name: 'Gunma' },
    { code: 'STM', name: 'Saitama' }, { code: 'CHB', name: 'Chiba' },
    { code: 'TKY', name: 'Tokyo' }, { code: 'KNG', name: 'Kanagawa' },
    { code: 'NGT', name: 'Niigata' }, { code: 'TYM', name: 'Toyama' },
    { code: 'ISK', name: 'Ishikawa' }, { code: 'FKI', name: 'Fukui' },
    { code: 'YMN', name: 'Yamanashi' }, { code: 'NGN', name: 'Nagano' },
    { code: 'SZO', name: 'Shizuoka' }, { code: 'AIC', name: 'Aichi' },
    { code: 'MIE', name: 'Mie' }, { code: 'SHG', name: 'Shiga' },
    { code: 'KYT', name: 'Kyoto' }, { code: 'OSK', name: 'Osaka' },
    { code: 'HYG', name: 'Hyogo' }, { code: 'NRA', name: 'Nara' },
    { code: 'WKY', name: 'Wakayama' }, { code: 'TTR', name: 'Tottori' },
    { code: 'SMN', name: 'Shimane' }, { code: 'OKY', name: 'Okayama' },
    { code: 'HRS', name: 'Hiroshima' }, { code: 'YGC', name: 'Yamaguchi' },
    { code: 'TKS', name: 'Tokushima' }, { code: 'KGW', name: 'Kagawa' },
    { code: 'EHM', name: 'Ehime' }, { code: 'KCH', name: 'Kochi' },
    { code: 'FKO', name: 'Fukuoka' }, { code: 'SAG', name: 'Saga' },
    { code: 'NGS', name: 'Nagasaki' }, { code: 'KMT', name: 'Kumamoto' },
    { code: 'OIT', name: 'Oita' }, { code: 'MYZ', name: 'Miyazaki' },
    { code: 'KGS', name: 'Kagoshima' }, { code: 'OKN', name: 'Okinawa' },
  ],
};

// Cities per state (comprehensive for US, major cities for others)
export const CITIES: Record<string, string[]> = {
  // US States
  'US-AL': ['Birmingham', 'Montgomery', 'Huntsville', 'Mobile', 'Tuscaloosa', 'Hoover', 'Dothan', 'Auburn', 'Decatur', 'Madison', 'Florence', 'Gadsden', 'Vestavia Hills', 'Prattville', 'Phenix City'],
  'US-AK': ['Anchorage', 'Fairbanks', 'Juneau', 'Sitka', 'Ketchikan', 'Wasilla', 'Kenai', 'Kodiak', 'Bethel', 'Palmer', 'Homer', 'Unalaska', 'Barrow', 'Soldotna', 'Valdez'],
  'US-AZ': ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale', 'Glendale', 'Gilbert', 'Tempe', 'Peoria', 'Surprise', 'Yuma', 'Avondale', 'Flagstaff', 'Goodyear', 'Lake Havasu City', 'Buckeye', 'Casa Grande', 'Sierra Vista', 'Maricopa', 'Oro Valley', 'Prescott', 'Kingman', 'Marana', 'Bullhead City', 'Nogales'],
  'US-AR': ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro', 'North Little Rock', 'Conway', 'Rogers', 'Pine Bluff', 'Bentonville', 'Hot Springs', 'Benton', 'Texarkana', 'Sherwood', 'Jacksonville'],
  'US-CA': ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno', 'Sacramento', 'Long Beach', 'Oakland', 'Bakersfield', 'Anaheim', 'Santa Ana', 'Riverside', 'Stockton', 'Chula Vista', 'Irvine', 'Fremont', 'San Bernardino', 'Modesto', 'Fontana', 'Moreno Valley', 'Glendale', 'Huntington Beach', 'Santa Clarita', 'Garden Grove', 'Oceanside', 'Rancho Cucamonga', 'Santa Rosa', 'Ontario', 'Elk Grove', 'Hayward', 'Salinas', 'Sunnyvale', 'Torrance', 'Corona', 'Escondido', 'Pasadena', 'Fullerton', 'Orange', 'Pomona', 'Visalia', 'Thousand Oaks', 'Concord', 'Simi Valley', 'Victorville', 'Santa Clara', 'Berkeley', 'Roseville', 'El Monte', 'Inglewood'],
  'US-CO': ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood', 'Thornton', 'Arvada', 'Westminster', 'Pueblo', 'Centennial', 'Boulder', 'Highland Ranch', 'Highlands Ranch', 'Greeley', 'Longmont', 'Loveland', 'Broomfield', 'Lakewood', 'Castle Rock', 'Commerce City', 'Parker', 'Northglenn', 'Brighton', 'Security-Widefield', 'Pueblo West'],
  'US-CT': ['Bridgeport', 'New Haven', 'Hartford', 'Stamford', 'Waterbury', 'Norwalk', 'Danbury', 'New Britain', 'Bristol', 'Meriden', 'West Haven', 'Milford', 'Stratford', 'East Hartford', 'Middletown', 'Enfield', 'Hamden', 'Manchester', 'Torrington', 'Greenwich'],
  'US-DE': ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Bear', 'Glasgow', 'Brookside', 'Hockessin', 'Claymont', 'Smyrna', 'Milford', 'Seaford', 'Georgetown', 'Elsmere', 'New Castle'],
  'US-FL': ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg', 'Hialeah', 'Port St. Lucie', 'Tallahassee', 'Cape Coral', 'Fort Lauderdale', 'Pembroke Pines', 'Hollywood', 'Miramar', 'Gainesville', 'Coral Springs', 'Clearwater', 'Palm Bay', 'Pompano Beach', 'West Palm Beach', 'Lakeland', 'Davie', 'Miami Gardens', 'Sunrise', 'Boca Raton', 'Deltona', 'Plantation', 'Alafaya', 'Largo', 'Deerfield Beach', 'Melbourne', 'Boynton Beach', 'Lauderhill', 'Wichita Falls', 'Brandon', 'Palm Beach Gardens', 'Daytona Beach', 'Homestead', 'Kissimmee', 'North Port', 'Doral', 'Tamarac', 'Wellington', 'Ocala', 'Pensacola', 'Fort Myers', 'Naples'],
  'US-GA': ['Atlanta', 'Augusta', 'Columbus', 'Macon', 'Savannah', 'Athens', 'Sandy Springs', 'Roswell', 'Johns Creek', 'Albany', 'Warner Robins', 'Alpharetta', 'Marietta', 'Valdosta', 'Smyrna', 'Dunwoody', 'Brookhaven', 'Peachtree City', 'Rome', 'Gainesville', 'Columbus', 'Dalton', 'Kennesaw', 'Newnan', 'Hinesville'],
  'US-HI': ['Honolulu', 'Pearl City', 'Hilo', 'Kailua', 'Waipahu', 'Kaneohe', 'Mililani Town', 'Kahului', 'Ewa Gentry', 'Mililani Mauka', 'Kihei', 'Makakilo', 'Wahiawa', 'Wailuku', 'Kapolei', 'Ewa Beach', 'Halawa', 'Waimalu', 'Waipio', 'Lahaina'],
  'US-ID': ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Pocatello', 'Caldwell', 'Coeur d\'Alene', 'Twin Falls', 'Lewiston', 'Post Falls', 'Rexburg', 'Moscow', 'Eagle', 'Chubbuck', 'Hayden', 'Mountain Home', 'Kuna', 'Ammon', 'Blackfoot', 'Garden City'],
  'US-IL': ['Chicago', 'Aurora', 'Joliet', 'Naperville', 'Rockford', 'Springfield', 'Elgin', 'Peoria', 'Champaign', 'Waukegan', 'Cicero', 'Bloomington', 'Evanston', 'Decatur', 'Arlington Heights', 'Bolingbrook', 'Des Plaines', 'Orland Park', 'Skokie', 'Tinley Park', 'Oak Lawn', 'Berwyn', 'Mount Prospect', 'Downers Grove', 'Normal', 'Wheaton', 'Hoffman Estates', 'Plainfield', 'Gurnee', 'Aurora'],
  'US-IN': ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel', 'Fishers', 'Bloomington', 'Hammond', 'Gary', 'Lafayette', 'Muncie', 'Terre Haute', 'Kokomo', 'Anderson', 'Noblesville', 'Greenwood', 'Elkhart', 'Mishawaka', 'Lawrence', 'Jeffersonville'],
  'US-IA': ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City', 'Waterloo', 'Council Bluffs', 'Ames', 'Dubuque', 'West Des Moines', 'Ankeny', 'Urbandale', 'Cedar Falls', 'Marion', 'Bettendorf', 'Waukee', 'Johnston', 'Mason City', 'North Liberty', 'Coralville'],
  'US-KS': ['Wichita', 'Overland Park', 'Kansas City', 'Olathe', 'Topeka', 'Lawrence', 'Shawnee', 'Manhattan', 'Lenexa', 'Salina', 'Hutchinson', 'Leavenworth', 'Leawood', 'Dodge City', 'Garden City', 'Junction City', 'Emporia', 'Derby', 'Prairie Village', 'Liberal'],
  'US-KY': ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington', 'Richmond', 'Georgetown', 'Florence', 'Henderson', 'Elizabethtown', 'Nicholasville', 'Hopkinsville', 'Frankfort', 'Paducah', 'Jeffersontown', 'Radcliff', 'Ashland', 'Independence', 'Murray', 'Erlanger'],
  'US-LA': ['New Orleans', 'Baton Rouge', 'Shreveport', 'Metairie', 'Lafayette', 'Lake Charles', 'Bossier City', 'Monroe', 'Alexandria', 'Kenner', 'New Iberia', 'Prairieville', 'Sulphur', 'Laplace', 'Slidell', 'Hammond', 'Houma', 'Mandeville', 'Natchitoches', 'Ruston'],
  'US-ME': ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn', 'Biddeford', 'Sanford', 'Saco', 'Augusta', 'Westbrook', 'Waterville', 'Presque Isle', 'Brewer', 'Bath', 'Caribou', 'Ellsworth', 'Old Town', 'Rockland', 'Belfast', 'Gardiner'],
  'US-MD': ['Baltimore', 'Frederick', 'Rockville', 'Gaithersburg', 'Bowie', 'Hagerstown', 'Annapolis', 'College Park', 'Salisbury', 'Laurel', 'Greenbelt', 'Cumberland', 'Westminster', 'Hyattsville', 'Takoma Park', 'Easton', 'Germantown', 'Waldorf', 'Silver Spring', 'Ellicott City'],
  'US-MA': ['Boston', 'Worcester', 'Springfield', 'Lowell', 'Cambridge', 'New Bedford', 'Brockton', 'Quincy', 'Lynn', 'Fall River', 'Newton', 'Lawrence', 'Somerville', 'Haverhill', 'Waltham', 'Malden', 'Medford', 'Taunton', 'Chicopee', 'Revere', 'Peabody', 'Barnstable', 'Pittsfield', 'Attleboro', 'Weymouth'],
  'US-MI': ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor', 'Lansing', 'Flint', 'Dearborn', 'Livonia', 'Westland', 'Troy', 'Farmington Hills', 'Kalamazoo', 'Wyoming', 'Southfield', 'Rochester Hills', 'Taylor', 'Pontiac', 'St. Clair Shores', 'Royal Oak', 'Novi', 'Dearborn Heights', 'Battle Creek', 'Muskegon', 'Saginaw'],
  'US-MN': ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth', 'Bloomington', 'Brooklyn Park', 'Plymouth', 'Maple Grove', 'Woodbury', 'Saint Cloud', 'Eagan', 'Eden Prairie', 'Coon Rapids', 'Blaine', 'Burnsville', 'Apple Valley', 'Edina', 'Minnetonka', 'Lakeville', 'Mankato'],
  'US-MS': ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi', 'Meridian', 'Tupelo', 'Olive Branch', 'Horn Lake', 'Clinton', 'Madison', 'Pearl', 'Ridgeland', 'Greenville', 'Brandon', 'Oxford', 'Starkville', 'Vicksburg', 'Pascagoula', 'Gautier'],
  'US-MO': ['Kansas City', 'Saint Louis', 'Springfield', 'Columbia', 'Independence', "Lee's Summit", 'O\'Fallon', "St. Joseph", 'St. Charles', 'Blue Springs', 'Joplin', 'Florissant', 'Chesterfield', 'Jefferson City', 'Cape Girardeau', 'Wentzville', 'Wildwood', 'Ballwin', 'University City', 'Hazelwood'],
  'US-MT': ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Butte', 'Helena', 'Kalispell', 'Havre', 'Anaconda', 'Miles City', 'Livingston', 'Laurel', 'Whitefish', 'Belgrade', 'Lewistown', 'Sidney', 'Glendive', 'Dillon', 'Hardin', 'Cut Bank'],
  'US-NE': ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney', 'Fremont', 'Hastings', 'Norfolk', 'North Platte', 'Columbus', 'Papillion', 'La Vista', 'Scottsbluff', 'South Sioux City', 'Beatrice', 'Lexington', 'Gering', 'Alliance', 'Blair', 'York'],
  'US-NV': ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks', 'Carson City', 'Fernley', 'Elko', 'Mesquite', 'Boulder City', 'Fallon', 'Winnemucca', 'West Wendover', 'Ely', 'Yerington', 'Laughlin', 'Minden', 'Gardnerville', 'Pahrump', 'Sun Valley'],
  'US-NH': ['Manchester', 'Nashua', 'Concord', 'Derry', 'Rochester', 'Salem', 'Dover', 'Merrimack', 'Londonderry', 'Hudson', 'Keene', 'Portsmouth', 'Bedford', 'Goffstown', 'Laconia', 'Hampton', 'Milford', 'Durham', 'Exeter', 'Windham'],
  'US-NJ': ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Edison', 'Woodbridge', 'Lakewood', 'Toms River', 'Hamilton', 'Trenton', 'Clifton', 'Camden', 'Brick', 'Cherry Hill', 'Passaic', 'Middletown', 'Union City', 'Old Bridge', 'Gloucester', 'East Orange', 'Bayonne', 'North Bergen', 'Vineland', 'Union', 'Piscataway'],
  'US-NM': ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell', 'Farmington', 'Clovis', 'Hobbs', 'Alamogordo', 'Carlsbad', 'Gallup', 'Deming', 'Los Lunas', 'Chaparral', 'Sunland Park', 'Las Vegas', 'Portales', 'Artesia', 'Lovington', 'Silver City'],
  'US-NY': ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse', 'Albany', 'New Rochelle', 'Mount Vernon', 'Schenectady', 'Utica', 'White Plains', 'Hempstead', 'Troy', 'Niagara Falls', 'Binghamton', 'Freeport', 'Valley Stream', 'Long Beach', 'Rome', 'North Hempstead', 'Spring Valley', 'Ithaca', 'Cheektowaga', 'Brooklyn', 'Manhattan', 'Queens', 'Bronx', 'Staten Island'],
  'US-NC': ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem', 'Fayetteville', 'Cary', 'Wilmington', 'High Point', 'Concord', 'Asheville', 'Gastonia', 'Chapel Hill', 'Rocky Mount', 'Huntersville', 'Burlington', 'Wilson', 'Kannapolis', 'Apex', 'Greenville', 'Matthews', 'Jacksonville', 'Indian Trail', 'Mooresville', 'Hickory'],
  'US-ND': ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo', 'Williston', 'Dickinson', 'Mandan', 'Jamestown', 'Wahpeton', 'Devils Lake', 'Watford City', 'Valley City', 'Grafton', 'Lincoln', 'Beulah', 'Rugby', 'Bottineau', 'Lisbon', 'Hazen'],
  'US-OH': ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton', 'Parma', 'Canton', 'Youngstown', 'Lorain', 'Hamilton', 'Springfield', 'Kettering', 'Elyria', 'Lakewood', 'Cuyahoga Falls', 'Middletown', 'Euclid', 'Newark', 'Mansfield', 'Mentor', 'Beavercreek', 'Cleveland Heights', 'Strongsville', 'Dublin', 'Fairfield', 'Lima', 'Huber Heights', 'Westerville', 'Reynoldsburg'],
  'US-OK': ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond', 'Lawton', 'Moore', 'Midwest City', 'Enid', 'Stillwater', 'Muskogee', 'Bartlesville', 'Owasso', 'Shawnee', 'Ponca City', 'Ardmore', 'Bixby', 'Sapulpa', 'Yukon', 'Altus'],
  'US-OR': ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro', 'Beaverton', 'Bend', 'Medford', 'Springfield', 'Corvallis', 'Albany', 'Tigard', 'Lake Oswego', 'Keizer', 'Grants Pass', 'Oregon City', 'McMinnville', 'Redmond', 'Tualatin', 'West Linn'],
  'US-PA': ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading', 'Scranton', 'Bethlehem', 'Lancaster', 'Harrisburg', 'Altoona', 'York', 'Wilkes-Barre', 'Chester', 'Norristown', 'State College', 'Bethel Park', 'Monroeville', 'Drexel Hill', 'Plum', 'Bensalem', 'Abington', 'Upper Darby', 'Penn Hills', 'Williamsport', 'Easton'],
  'US-RI': ['Providence', 'Cranston', 'Warwick', 'Pawtucket', 'East Providence', 'Woonsocket', 'Coventry', 'Cumberland', 'North Providence', 'South Kingstown', 'West Warwick', 'Johnston', 'North Kingstown', 'Newport', 'Bristol', 'Lincoln', 'Smithfield', 'Central Falls', 'Portsmouth', 'Barrington'],
  'US-SC': ['Columbia', 'Charleston', 'North Charleston', 'Mount Pleasant', 'Rock Hill', 'Greenville', 'Summerville', 'Sumter', 'Goose Creek', 'Hilton Head Island', 'Florence', 'Spartanburg', 'Conway', 'Myrtle Beach', 'Aiken', 'Anderson', 'Mauldin', 'Greer', 'Greenwood', 'Taylors'],
  'US-SD': ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown', 'Mitchell', 'Yankton', 'Pierre', 'Huron', 'Vermillion', 'Spearfish', 'Brandon', 'Box Elder', 'Madison', 'Sturgis', 'Belle Fourche', 'Mobridge', 'Lead', 'Milbank', 'Harrisburg'],
  'US-TN': ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville', 'Murfreesboro', 'Franklin', 'Jackson', 'Johnson City', 'Bartlett', 'Hendersonville', 'Kingsport', 'Collierville', 'Smyrna', 'Cleveland', 'Brentwood', 'Germantown', 'Columbia', 'Spring Hill', 'La Vergne', 'Gallatin', 'Cookeville', 'Oak Ridge', 'Morristown', 'Bristol'],
  'US-TX': ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso', 'Arlington', 'Corpus Christi', 'Plano', 'Laredo', 'Lubbock', 'Garland', 'Irving', 'Amarillo', 'Grand Prairie', 'McKinney', 'Frisco', 'Brownsville', 'Pasadena', 'Killeen', 'McAllen', 'Mesquite', 'Denton', 'Waco', 'Carrollton', 'Midland', 'Abilene', 'Beaumont', 'Round Rock', 'Odessa', 'Richardson', 'Tyler', 'Pearland', 'College Station', 'Lewisville', 'League City', 'Allen', 'Cedar Park', 'Wichita Falls', 'Sugar Land'],
  'US-UT': ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem', 'Sandy', 'Ogden', 'St. George', 'Layton', 'South Jordan', 'Millcreek', 'Taylorsville', 'Logan', 'Murray', 'Draper', 'Bountiful', 'Lehi', 'Riverton', 'Roy', 'Spanish Fork', 'Herriman', 'American Fork', 'Clearfield', 'Vineyard', 'Cedar City'],
  'US-VT': ['Burlington', 'South Burlington', 'Rutland', 'Barre', 'Montpelier', 'Winooski', 'St. Albans', 'Newport', 'Vergennes', 'Middlebury', 'Johnson', 'Swanton', 'Morrisville', 'St. Johnsbury', 'Springfield', 'White River Junction', 'Brattleboro', 'Bellows Falls', 'Bennington', 'Lyndonville'],
  'US-VA': ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Newport News', 'Alexandria', 'Hampton', 'Roanoke', 'Portsmouth', 'Suffolk', 'Lynchburg', 'Harrisonburg', 'Leesburg', 'Charlottesville', 'Danville', 'Blacksburg', 'Manassas', 'Petersburg', 'Falls Church', 'Fredericksburg', 'McLean', 'Herndon', 'Sterling', 'Reston', 'Burke'],
  'US-WA': ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue', 'Kent', 'Everett', 'Renton', 'Spokane Valley', 'Federal Way', 'Kirkland', 'Bellingham', 'Kennewick', 'Yakima', 'Redmond', 'Marysville', 'Pasco', 'Newcastle', 'Lakewood', 'Shoreline', 'Richland', 'South Hill', 'Sammamish', 'Burien', 'Des Moines'],
  'US-WV': ['Charleston', 'Huntington', 'Parkersburg', 'Morgantown', 'Wheeling', 'Weirton', 'Fairmont', 'Martinsburg', 'Beckley', 'Clarksburg', 'South Charleston', 'St. Albans', 'Vienna', 'Bluefield', 'Moundsville', 'Bridgeport', 'Oak Hill', 'Dunbar', 'Elkins', 'Hurricane'],
  'US-WI': ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine', 'Appleton', 'Waukesha', 'Eau Claire', 'Oshkosh', 'Janesville', 'West Allis', 'La Crosse', 'Sheboygan', 'Wauwatosa', 'Fond du Lac', 'New Berlin', 'Wausau', 'Brookfield', 'Beloit', 'Greenfield', 'Franklin', 'Oak Creek', 'Manitowoc', 'West Bend', 'Superior'],
  'US-WY': ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs', 'Sheridan', 'Green River', 'Evanston', 'Riverton', 'Jackson', 'Cody', 'Rawlins', 'Lander', 'Torrington', 'Powell', 'Douglas', 'Worland', 'Thermopolis', 'Wheatland', 'Buffalo'],
  'US-DC': ['Washington'],

  // Canada
  'CA-AB': ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge', 'Sherwood Park', 'St. Albert', 'Medicine Hat', 'Grande Prairie', 'Airdrie', 'Spruce Grove', 'Leduc', 'Cochrane', 'Fort McMurray', 'Camrose', 'Lloydminster'],
  'CA-BC': ['Vancouver', 'Surrey', 'Burnaby', 'Richmond', 'Kelowna', 'Abbotsford', 'Coquitlam', 'Langley', 'Saanich', 'Delta', 'Kamloops', 'Nanaimo', 'Victoria', 'Chilliwack', 'Prince George', 'Vernon', 'Courtenay', 'Penticton', 'Maple Ridge', 'North Vancouver'],
  'CA-MB': ['Winnipeg', 'Brandon', 'Steinbach', 'Thompson', 'Portage la Prairie', 'Winkler', 'Selkirk', 'Morden', 'Dauphin', 'The Pas', 'Flin Flon', 'Kenora', 'Swan River', 'Minnedosa', 'Neepawa'],
  'CA-NB': ['Moncton', 'Saint John', 'Fredericton', 'Dieppe', 'Riverview', 'Miramichi', 'Edmundston', 'Bathurst', 'Campbellton', 'Oromocto', 'Grand Falls', 'Quispamsis', 'Rothesay', 'Sussex', 'Sackville'],
  'CA-NL': ['St. John\'s', 'Mount Pearl', 'Corner Brook', 'Conception Bay South', 'Paradise', 'Grand Falls-Windsor', 'Gander', 'Happy Valley-Goose Bay', 'Labrador City', 'Stephenville', 'Marystown', 'Bay Roberts', 'Torbay', 'Channel-Port aux Basques', 'Clarenville'],
  'CA-NS': ['Halifax', 'Dartmouth', 'Sydney', 'Truro', 'New Glasgow', 'Glace Bay', 'Kentville', 'Amherst', 'Bridgewater', 'Yarmouth', 'Antigonish', 'Windsor', 'Digby', 'Wolfville', 'Stellarton'],
  'CA-ON': ['Toronto', 'Ottawa', 'Mississauga', 'Brampton', 'Hamilton', 'London', 'Markham', 'Vaughan', 'Kitchener', 'Windsor', 'Niagara Falls', 'Barrie', 'Richmond Hill', 'Burlington', 'Oshawa', 'Sudbury', 'Thunder Bay', 'Waterloo', 'Cambridge', 'Guelph', 'Kingston', 'Ajax', 'Whitby', 'Chatham', 'St. Catharines'],
  'CA-PE': ['Charlottetown', 'Summerside', 'Stratford', 'Cornwall', 'Montague', 'Kensington', 'Souris', 'Alberton', 'O\'Leary', 'Georgetown'],
  'CA-QC': ['Montreal', 'Quebec City', 'Laval', 'Gatineau', 'Longueuil', 'Sherbrooke', 'Saguenay', 'Lévis', 'Trois-Rivières', 'Terrebonne', 'Saint-Jean-sur-Richelieu', 'Repentigny', 'Brossard', 'Dollard-des-Ormeaux', 'Drummondville', 'Saint-Jérôme', 'Granby', 'Blainville', 'Shawinigan', 'Rimouski'],
  'CA-SK': ['Saskatoon', 'Regina', 'Prince Albert', 'Moose Jaw', 'Swift Current', 'Yorkton', 'North Battleford', 'Estevan', 'Weyburn', 'Lloydminster', 'Martensville', 'Warman', 'Humboldt', 'Melfort', 'Kindersley'],
  'CA-NT': ['Yellowknife', 'Hay River', 'Inuvik', 'Fort Smith', 'Behchoko'],
  'CA-NU': ['Iqaluit', 'Rankin Inlet', 'Arviat', 'Baker Lake', 'Cambridge Bay'],
  'CA-YT': ['Whitehorse', 'Dawson City', 'Watson Lake', 'Haines Junction', 'Carmacks'],

  // Australia
  'AU-NSW': ['Sydney', 'Newcastle', 'Wollongong', 'Maitland', 'Central Coast', 'Wagga Wagga', 'Albury', 'Tamworth', 'Orange', 'Dubbo', 'Bowral', 'Bathurst', 'Nowra', 'Port Macquarie', 'Lismore', 'Griffith', 'Armidale', 'Coffs Harbour', 'Broken Hill', 'Queanbeyan'],
  'AU-VIC': ['Melbourne', 'Geelong', 'Ballarat', 'Bendigo', 'Shepparton', 'Mildura', 'Wodonga', 'Warrnambool', 'Traralgon', 'Wangaratta', 'Sale', 'Horsham', 'Bairnsdale', 'Colac', 'Hamilton', 'Stawell', 'Echuca', 'Swan Hill', 'Moe', 'Portland'],
  'AU-QLD': ['Brisbane', 'Gold Coast', 'Sunshine Coast', 'Townsville', 'Cairns', 'Toowoomba', 'Mackay', 'Rockhampton', 'Bundaberg', 'Hervey Bay', 'Gladstone', 'Mount Isa', 'Emerald', 'Innisfail', 'Gympie', 'Maryborough', 'Warwick', 'Dalby', 'Stanthorpe', 'Roma'],
  'AU-SA': ['Adelaide', 'Mount Gambier', 'Whyalla', 'Murray Bridge', 'Port Augusta', 'Victor Harbor', 'Port Pirie', 'Gawler', 'Kadina', 'Port Lincoln', 'Naracoorte', 'Berri', 'Renmark', 'Clare', 'Mount Barker'],
  'AU-WA': ['Perth', 'Mandurah', 'Bunbury', 'Geraldton', 'Kalgoorlie', 'Albany', 'Broome', 'Karratha', 'Port Hedland', 'Busselton', 'Esperance', 'Northam', 'Carnarvon', 'Newman', 'Tom Price'],
  'AU-TAS': ['Hobart', 'Launceston', 'Devonport', 'Burnie', 'Ulverstone', 'Queenstown', 'George Town', 'New Norfolk', 'Sorell', 'Scottsdale'],
  'AU-NT': ['Darwin', 'Alice Springs', 'Palmerston', 'Katherine', 'Nhulunbuy', 'Tennant Creek', 'Jabiru'],
  'AU-ACT': ['Canberra', 'Tuggeranong', 'Belconnen', 'Woden', 'Gungahlin', 'Weston Creek'],

  // UK
  'GB-ENG': ['London', 'Birmingham', 'Manchester', 'Leeds', 'Liverpool', 'Sheffield', 'Bristol', 'Leicester', 'Coventry', 'Bradford', 'Nottingham', 'Newcastle upon Tyne', 'Sunderland', 'Brighton', 'Plymouth', 'Derby', 'Wolverhampton', 'Southampton', 'Portsmouth', 'Norwich', 'Reading', 'Middlesbrough', 'Stoke-on-Trent', 'Preston', 'York', 'Peterborough', 'Exeter', 'Cambridge', 'Oxford', 'Gloucester'],
  'GB-SCT': ['Glasgow', 'Edinburgh', 'Aberdeen', 'Dundee', 'Inverness', 'Perth', 'Stirling', 'Livingston', 'Ayr', 'Kilmarnock', 'Cumbernauld', 'Paisley', 'Hamilton', 'East Kilbride', 'Motherwell'],
  'GB-WLS': ['Cardiff', 'Swansea', 'Newport', 'Bridgend', 'Wrexham', 'Barry', 'Neath', 'Port Talbot', 'Rhondda', 'Llanelli', 'Merthyr Tydfil', 'Caerphilly', 'Cwmbran', 'Bangor', 'Aberystwyth'],
  'GB-NIR': ['Belfast', 'Derry', 'Lisburn', 'Newry', 'Armagh', 'Omagh', 'Dungannon', 'Enniskillen', 'Antrim', 'Ballymena', 'Coleraine', 'Ballymoney', 'Larne', 'Strabane', 'Bangor'],

  // New Zealand
  'NZ-AUK': ['Auckland', 'Manukau', 'North Shore', 'Waitakere', 'Papakura', 'Pukekohe', 'Warkworth', 'Helensville'],
  'NZ-WGN': ['Wellington', 'Lower Hutt', 'Upper Hutt', 'Porirua', 'Kapiti'],
  'NZ-CAN': ['Christchurch', 'Timaru', 'Ashburton', 'Kaikoura', 'Greymouth'],
  'NZ-WKO': ['Hamilton', 'Tauranga', 'Rotorua', 'Taupo', 'Tokoroa', 'Cambridge'],
  'NZ-OTA': ['Dunedin', 'Invercargill', 'Queenstown', 'Alexandra', 'Oamaru'],
  'NZ-BOP': ['Tauranga', 'Whakatane', 'Rotorua', 'Opotiki', 'Katikati'],
  'NZ-HKB': ['Napier', 'Hastings', 'Wairoa', 'Waipukurau'],
  'NZ-MWT': ['Palmerston North', 'Whanganui', 'Levin', 'Feilding', 'Marton'],
  'NZ-NTL': ['Whangarei', 'Kerikeri', 'Kaitaia', 'Dargaville', 'Paihia'],
  'NZ-TAS': ['Nelson', 'Motueka', 'Richmond'],
  'NZ-MBH': ['Blenheim', 'Picton', 'Havelock'],
  'NZ-NSN': ['Nelson', 'Motueka', 'Wakefield'],
  'NZ-GIS': ['Gisborne', 'Wairoa', 'Ruatoria'],
  'NZ-TKI': ['New Plymouth', 'Stratford', 'Hawera', 'Waitara'],
  'NZ-STL': ['Invercargill', 'Gore', 'Winton', 'Bluff'],
  'NZ-WTC': ['Greymouth', 'Westport', 'Hokitika', 'Reefton'],

  // South Africa
  'ZA-GP': ['Johannesburg', 'Pretoria', 'Soweto', 'Benoni', 'Boksburg', 'Sandton', 'Randburg', 'Midrand', 'Germiston', 'Centurion', 'Tembisa', 'Roodepoort', 'Krugersdorp', 'Springs'],
  'ZA-WC': ['Cape Town', 'Bellville', 'George', 'Worcester', 'Stellenbosch', 'Paarl', 'Knysna', 'Mossel Bay', 'Hermanus', 'Oudtshoorn', 'Somerset West', 'Strand'],
  'ZA-KZN': ['Durban', 'Pietermaritzburg', 'Newcastle', 'Chatsworth', 'Richards Bay', 'Ladysmith', 'Port Shepstone', 'Pinetown', 'Tongaat', 'Empangeni', 'Umlazi'],
  'ZA-EC': ['Port Elizabeth', 'East London', 'Mthatha', 'Uitenhage', 'King William\'s Town', 'Queenstown', 'Grahamstown', 'Graaff-Reinet', 'Aliwal North', 'Butterworth'],
  'ZA-FS': ['Bloemfontein', 'Welkom', 'Botshabelo', 'Bethlehem', 'Kroonstad', 'Sasolburg', 'Phuthaditjhaba', 'Harrismith', 'Virginia', 'Odendaalsrus'],
  'ZA-LP': ['Polokwane', 'Tzaneen', 'Thohoyandou', 'Mokopane', 'Lephalale', 'Bela-Bela', 'Giyani', 'Louis Trichardt', 'Phalaborwa', 'Musina'],
  'ZA-MP': ['Nelspruit', 'Witbank', 'Secunda', 'Middelburg', 'Standerton', 'Hendrina', 'Lydenburg', 'Barberton', 'Piet Retief', 'Ermelo'],
  'ZA-NC': ['Kimberley', 'Upington', 'De Aar', 'Springbok', 'Kuruman', 'Jan Kempdorp', 'Prieska', 'Calvinia', 'Carnarvon'],
  'ZA-NW': ['Rustenburg', 'Potchefstroom', 'Klerksdorp', 'Mafikeng', 'Brits', 'Orkney', 'Stilfontein', 'Lichtenburg', 'Vryburg', 'Zeerust'],
};

export function getCitiesForState(countryCode: string, stateCode: string): string[] {
  const key = `${countryCode}-${stateCode}`;
  return CITIES[key] || [];
}

export function getStatesForCountry(countryCode: string): { code: string; name: string }[] {
  return STATES[countryCode] || [];
}

export function getCountryByCode(code: string): CountryData | undefined {
  return COUNTRIES.find(c => c.code === code);
}
